-- Out-of-band confirmation ledger for high-risk AI write operations.
-- When SAFE_MODE blocks a write, we insert a row here (approved=false). The
-- user approves via POST /api/confirmations/:id/approve (which only a real
-- user session can call, AI cannot). The tool wrapper then checks this
-- table before allowing the retry, and marks the row consumed so it can't
-- be reused. Rows expire after 10 min.
-- Run this in the Supabase SQL Editor.

CREATE TABLE IF NOT EXISTS pending_confirmations (
  id            text PRIMARY KEY,             -- uuid generated by server
  fb_user_id    text,                         -- owner (may be null if token missing)
  session_id    text,                         -- chat/adk session id
  tool_name     text NOT NULL,
  args          jsonb NOT NULL,               -- exact args to match on retry
  args_hash     text NOT NULL,                -- sha256 of canonical args (fast match)
  reason        text,                         -- why it was flagged
  approved      boolean NOT NULL DEFAULT false,
  approved_at   timestamptz,
  consumed      boolean NOT NULL DEFAULT false,
  consumed_at   timestamptz,
  created_at    timestamptz NOT NULL DEFAULT now(),
  expires_at    timestamptz NOT NULL DEFAULT (now() + interval '10 minutes')
);

CREATE INDEX IF NOT EXISTS idx_pending_confirmations_user
  ON pending_confirmations(fb_user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_pending_confirmations_session
  ON pending_confirmations(session_id, approved, consumed);
